"""
Barcode normalisation and SKU construction.

WHY THIS MODULE CARRIES MORE RISK THAN ITS SIZE SUGGESTS
========================================================
A supplier feed and an Amazon catalogue routinely disagree about how to write
the same barcode, and getting that disagreement wrong fails *silently*.

The failure mode is what makes it dangerous. Amazon does not reject an update
addressed to a SKU that does not exist -- it accepts the call and does nothing.
So a normalisation bug does not surface as an error, a stack trace, or a failed
run. It surfaces as a subset of the catalogue that quietly stops being synced,
and it can stay that way indefinitely.

The two conventions that have to be reconciled:

  * **Feeds tend to strip leading zeros.** A barcode is usually carried as a
    number somewhere upstream -- a spreadsheet cell, a CSV column, an integer
    database field -- and every one of those drops a leading zero. So the same
    product can arrive as an 11- or 12-digit string that is not a well-formed
    GTIN at all, even though it becomes one the moment the zero is restored.

  * **Amazon SKUs are usually zero-padded to a fixed width.** Whatever width a
    catalogue was built with, it is applied consistently, because the SKU is a
    string and was generated by something that padded it.

Reconciling those is the whole job: pad to :data:`CANONICAL_WIDTH`, always.

WHY THE CHECK DIGIT MATTERS HERE
--------------------------------
Stripping is not the only reason a short barcode appears. Feeds also contain
genuine junk -- truncated values, partial entries, data-entry mistakes. The two
cases need opposite treatment: a stripped code should be recovered, junk must
never be turned into a SKU and sent anywhere.

The GTIN check digit separates them. If a short code becomes checksum-valid
once a leading zero is restored, a zero was almost certainly stripped. If it
does not, it is far more likely to be rubbish. That distinction is the
difference between recovering a large slice of the catalogue and discarding it.

Note that validity is used as a *ranking signal*, never as a gate -- see
:func:`normalise`. Real catalogues contain listings whose barcode genuinely
fails the checksum, and refusing to match those would orphan real products.

WORKED EXAMPLE (illustrative figures, not measurements)
-------------------------------------------------------
Suppose a catalogue of 40,000 listings whose SKUs are ``EXAMPLE-`` plus a
13-digit zero-padded barcode, and a feed that strips leading zeros. If roughly
two thirds of those barcodes have at least one leading zero, then building the
SKU by naive concatenation::

    sku = "EXAMPLE-" + raw_feed_barcode      # wrong

matches only the third that never had a zero to lose. The other two thirds are
addressed as SKUs that do not exist, and are silently skipped. Everything in
this module exists to make that mistake impossible to commit by accident.

REFERENCES
----------
GTIN check digit: the last digit is a modulo-10 checksum over the preceding
digits with alternating 3/1 weights, counted from the right. Because the weight
pattern is anchored at the right-hand end, zero-padding a code on the left does
not change its check digit -- which is precisely why padding and validation can
be reasoned about independently.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: The width Amazon SKUs pad the barcode to. 13 (EAN-13) is the common choice
#: because it is the widest of the everyday retail formats, so UPC-A and EAN-8
#: codes pad into it without collision. If your catalogue was built to a
#: different width, this is the one constant to change.
CANONICAL_WIDTH = 13

#: Anything shorter than this is not a recoverable barcode. The shortest retail
#: barcode in use is EAN-8; feeds also carry rows with 1-7 characters, which are
#: data-entry rubbish and must never be turned into a SKU.
MIN_PLAUSIBLE_LENGTH = 8

#: GTIN-14 exists (shipping containers / outer cases). Catalogues generally hold
#: a small number of them, so they are tolerated as a match candidate rather
#: than discarded.
MAX_PLAUSIBLE_LENGTH = 14

_NON_DIGIT = re.compile(r"\D")

#: Pulls the digit block off the end of a SKU, e.g.
#: "EXAMPLE-0007298811035" -> "0007298811035".
#: Anchored at the end so suffixed SKUs like "ALT-7263956611093X" and
#: "SUP2-1234567890123-LN" do not produce a false digit run.
_SKU_TRAILING_DIGITS = re.compile(
    rf"(\d{{{MIN_PLAUSIBLE_LENGTH},{MAX_PLAUSIBLE_LENGTH}}})$"
)

#: Fallback for SKUs where the digits are not at the very end (e.g. a "-LN" or
#: "-V.G" condition suffix). Takes the LONGEST digit run anywhere in the SKU.
_SKU_ANY_DIGITS = re.compile(r"\d+")


# ---------------------------------------------------------------------------
# Check digit
# ---------------------------------------------------------------------------

def gtin_check_digit(body: str) -> str | None:
    """
    Compute the GTIN check digit for ``body`` (the code WITHOUT its final digit).

    The weighting alternates 3,1,3,1... counted from the RIGHTMOST body digit
    leftwards. That single rule covers UPC-A (12), EAN-13 and GTIN-14, which is
    why we do not need three separate implementations.

    Returns ``None`` if ``body`` is not all digits.

    >>> gtin_check_digit("00531905643")     # an illustrative code
    '4'
    >>> gtin_check_digit("111596244252")    # an illustrative EAN-13 body
    '8'
    """
    if not body or not body.isdigit():
        return None
    total = 0
    # enumerate from the right so the weight pattern is independent of length
    for i, ch in enumerate(reversed(body)):
        total += int(ch) * (3 if i % 2 == 0 else 1)
    return str((10 - total % 10) % 10)


def is_valid_gtin(code: str) -> bool:
    """
    True if ``code`` is a well-formed GTIN-8/12/13/14 including its check digit.

    Used to decide whether a short vendor barcode is "a stripped zero" (valid
    once padded) or "rubbish" (never valid). We deliberately do NOT reject
    invalid codes outright -- Amazon holds some listings whose barcode fails the
    checksum, and refusing to match them would orphan real products. Validity
    is a *ranking signal*, not a gate. See :func:`normalise`.
    """
    if not code or not code.isdigit():
        return False
    if len(code) not in (8, 12, 13, 14):
        return False
    return gtin_check_digit(code[:-1]) == code[-1]


# ---------------------------------------------------------------------------
# Normalisation
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class Barcode:
    """
    A vendor barcode after cleaning, with everything downstream code needs.

    Attributes
    ----------
    raw:
        Exactly what the vendor sent, untouched. Kept for audit trails so an
        operator can always see the original.
    digits:
        ``raw`` with every non-digit character removed and surrounding
        whitespace gone. Empty if there were no digits at all.
    canonical:
        ``digits`` zero-padded to :data:`CANONICAL_WIDTH`. **This is the value
        that gets concatenated with the SKU prefix.** Empty when the barcode is
        not usable.
    usable:
        False for rubbish (too short, no digits, or too long to be a GTIN).
        Unusable barcodes are logged to the rejects report and never pushed.
    checksum_ok:
        Whether :attr:`canonical` passes the GTIN check digit. Informational --
        a False here does not block a push, it only lowers match confidence.
    """

    raw: str
    digits: str
    canonical: str
    usable: bool
    checksum_ok: bool

    def __str__(self) -> str:  # pragma: no cover - convenience only
        return self.canonical or self.raw


def normalise(raw: str | int | None) -> Barcode:
    """
    Clean one vendor barcode and produce its canonical 13-digit form.

    This is the single entry point for every barcode that enters the system.
    Nothing else in the codebase is allowed to zero-pad by hand -- if you find
    yourself writing ``zfill(13)`` outside this module, use this instead, so
    the rule stays in one place.

    Handles, in order:
      1. ``None`` / blank            -> unusable
      2. Numbers that arrived as floats from a spreadsheet, e.g. 6.5103912346E10
         -- anything that has passed through a spreadsheet may carry barcodes
         as floats -> rendered as an integer string, not scientific notation
      3. Stray characters: spaces, hyphens, non-breaking spaces, quotes
      4. Junk shorter than :data:`MIN_PLAUSIBLE_LENGTH` -> unusable
      5. Anything longer than :data:`MAX_PLAUSIBLE_LENGTH` -> unusable
      6. Everything else -> zero-padded to 13

    >>> normalise("5319056434").canonical      # vendor strips zeros
    '0005319056434'
    >>> normalise("1115962442528").canonical   # already 13, untouched
    '1115962442528'
    >>> normalise("  535921-051355 ").canonical
    '0535921051355'
    >>> normalise("123").usable                # junk
    False
    >>> normalise(None).usable
    False
    """
    if raw is None:
        return Barcode("", "", "", False, False)

    # Spreadsheet exports hand us floats. int() first so 6.5103912346E10
    # becomes "65103912346" and not "1.2414152725e+10".
    if isinstance(raw, float):
        text = str(int(raw)) if raw == int(raw) else str(raw)
    elif isinstance(raw, int):
        text = str(raw)
    else:
        text = str(raw)

    digits = _NON_DIGIT.sub("", text.strip())

    if not digits:
        return Barcode(text, "", "", False, False)

    if len(digits) < MIN_PLAUSIBLE_LENGTH or len(digits) > MAX_PLAUSIBLE_LENGTH:
        # Deliberately unusable. The full feed contains ~150 such rows per day
        # (lengths 1-7). They are surfaced in the rejects report so somebody can
        # ask the vendor about them, but they never reach Amazon.
        return Barcode(text, digits, "", False, False)

    canonical = digits.zfill(CANONICAL_WIDTH) if len(digits) <= CANONICAL_WIDTH else digits
    return Barcode(
        raw=text,
        digits=digits,
        canonical=canonical,
        usable=True,
        checksum_ok=is_valid_gtin(canonical),
    )


def match_candidates(raw: str | int | None) -> list[str]:
    """
    Every form of a barcode worth trying when looking for a match, best first.

    Used by the mapping engine when the canonical 13-digit form does not find a
    listing. Real catalogues are messy: the same physical product can appear on
    Amazon as a 12-digit UPC, a 13-digit EAN, or (18 times on this account) a
    14-digit GTIN. Trying an ordered list of forms recovers those without ever
    guessing.

    Order matters -- the first hit wins, so the most trustworthy form is first:

      1. canonical 13-digit (the overwhelmingly common form)
      2. the digits exactly as the vendor sent them
      3. 12-digit UPC form
      4. 14-digit GTIN form
      5. zero-stripped form (in case Amazon is the one that stripped)

    Duplicates are removed while preserving order.

    >>> match_candidates("5319056434")
    ['0005319056434', '5319056434', '005319056434', '00005319056434']
    """
    bc = normalise(raw)
    if not bc.digits:
        return []

    ordered: list[str] = []
    d = bc.digits

    if bc.canonical:
        ordered.append(bc.canonical)
    ordered.append(d)
    if len(d) <= 12:
        ordered.append(d.zfill(12))
    if len(d) <= 14:
        ordered.append(d.zfill(14))
    stripped = d.lstrip("0")
    if stripped and stripped != d:
        ordered.append(stripped)

    seen: set[str] = set()
    out: list[str] = []
    for c in ordered:
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


# ---------------------------------------------------------------------------
# SKU construction and decomposition
# ---------------------------------------------------------------------------

def build_sku(prefix: str, raw_barcode: str | int | None) -> str | None:
    """
    Build the Amazon SKU for a vendor barcode.

    ``prefix`` comes from settings, so a new supplier or a changed SKU
    convention is a dashboard edit, not a release.

    Returns ``None`` when the barcode is unusable, which is the signal to skip
    the row rather than push a malformed SKU.

    >>> build_sku("EXAMPLE-", "7298811035")
    'EXAMPLE-0007298811035'
    >>> build_sku("EXAMPLE-", "4705343071514")
    'EXAMPLE-4705343071514'
    >>> build_sku("EXAMPLE-", "bad")
    """
    bc = normalise(raw_barcode)
    if not bc.usable or not bc.canonical:
        return None
    return f"{prefix}{bc.canonical}"


def candidate_skus(prefix: str, raw_barcode: str | int | None) -> list[str]:
    """
    Every SKU worth trying for one vendor barcode under one prefix, best first.

    Mirrors :func:`match_candidates` but in SKU space, for the tier of the
    mapping engine that searches by constructed SKU rather than by barcode.
    """
    return [f"{prefix}{c}" for c in match_candidates(raw_barcode)]


def split_sku(sku: str) -> tuple[str, str]:
    """
    Split an Amazon SKU into ``(prefix, barcode_digits)``.

    Needed because the All Listings Report on this account does **not** include
    a product-id column -- the only place the barcode appears is inside the SKU
    itself. So the mapping engine works backwards from the SKU.

    Returns ``("", "")`` if no digit block can be found.

    >>> split_sku("EXAMPLE-0007298811035")
    ('EXAMPLE-', '0007298811035')
    >>> split_sku("SUP2-1234567890123-LN")
    ('SUP2-', '1234567890123')
    >>> split_sku("0073555453232")          # some SKUs are a bare barcode
    ('', '0073555453232')
    >>> split_sku("ALT-7263956611093X")
    ('ALT-', '7263956611093')
    """
    s = (sku or "").strip()
    if not s:
        return "", ""

    m = _SKU_TRAILING_DIGITS.search(s)
    if m:
        return s[: m.start()], m.group(1)

    # No digits at the end -- take the longest digit run anywhere. This catches
    # condition-suffixed SKUs such as "SUP3-1234567890123-V.G".
    runs = _SKU_ANY_DIGITS.findall(s)
    if not runs:
        return s, ""
    best = max(runs, key=len)
    if len(best) < MIN_PLAUSIBLE_LENGTH:
        return s, ""
    idx = s.rfind(best)
    return s[:idx], best


def sku_prefix(sku: str) -> str:
    """
    The prefix part of a SKU, e.g. ``"EXAMPLE-"``.

    This is how the system decides whether a listing is in scope.

    A seller account that buys from several suppliers typically encodes the
    source in the SKU prefix, so the prefix is a reliable scope filter: listings
    under one prefix are backed by one supplier's feed, and listings under
    another prefix are backed by a feed this system never sees.

    That makes the prefix a safety boundary, not just a convenience. Pushing a
    quantity derived from supplier A's feed onto a listing sourced from supplier
    B would overwrite a correct quantity with an unrelated one. Scope is
    therefore enforced on this value. See :mod:`app.engine.mapping`.
    """
    return split_sku(sku)[0]


def barcode_from_sku(sku: str) -> Barcode:
    """
    Recover the canonical barcode from an Amazon SKU.

    Convenience wrapper used when building the Amazon-side index: it gives back
    a :class:`Barcode` so the same normalisation rules apply in both directions.
    """
    return normalise(split_sku(sku)[1])


# ---------------------------------------------------------------------------
# Bulk helpers
# ---------------------------------------------------------------------------

def normalise_many(raws: Iterable[str | int | None]) -> Iterator[Barcode]:
    """Stream-normalise a large iterable without building an intermediate list.

    A full feed runs to millions of rows; materialising them twice costs
    around a gigabyte of memory for no benefit.
    """
    for r in raws:
        yield normalise(r)
